---
title: "Estrutura básica de um modelo"
---

## Sobre o STAN

O STAN é um software que usa uma sintaxe própria para implementar seu algoritmo de amostragem MCMC. Por conta disso é comum que se diga que STAN é também uma linguagem de programação.
Como o STAN foi escrito em C++, sua sintaxe tem muitas similaridades com a dessa linguagem, mas também incorpora certos elementos de linguagens interpretadas como o R. Esse é o caso de estruturas como condições, laços e alguns operadores (como soma e multiplicação matriciais).

A principal diferença entre a sintaxe do Stan e a de linguagens interpretadas como o R é a tipagem. O Stan é fortemente tipado, o que significa que o tipo de cada variável deve ser declarado explicitamente. Isso se deve ao fato de que o compilador do Stan realiza uma série de otimizações para tornar o algoritmo de amostragem mais eficiente.

### Compilação vs. estimação {.unnumbered}

O uso do STAN pode ser dividido em duas etapas: compilação do modelo e construção da cadeia. Uma vez que o modelo está bem especificado (e o script STAN está pronto), é necessário compilar esse código em um arquivo executável (é esse arquivo que tomará amostras de uma cadeia MCMC). Note que 

### Sobre tipos primitivos {.unnumbered}

<!--
Declaração de suporte


The model must have support (non-zero density, equivalently finite log density) at parameter values that satisfy the declared constraints.

If this condition is violated with parameter values that satisfy declared constraints but do not have finite log density, then the samplers and optimizers may have any of a number of pathologies including just getting stuck, failure to initialize, excessive Metropolis rejection, or biased draws due to inability to explore the tails of the distribution.
-->

## Blocos 

Um modelo bayesiano está bem especificado se estão bem definidos os seguintes elementos:

* espaço paramétrico
* espaço amostral
* verossimilhança (ou a distribuição dos dados condicionados aos parâmetros) 
* distribuições prioris dos parâmetros

### Bloco data & transformed data {.unnumbered}

O bloco `data` é onde são declaradas as variáveis que o usuário deve passar   ao compilador, podendo ser interpretado como os argumentos de uma função. Já no bloco `transformed data`, é possível realizar operações sobre essas variáveis. Em resumo, o bloco data deve conter apenas declarações, não sendo permitido atribuir valores a variáveis dentro dele. Caso se queira atribuir ou modificar valores, isso deve ser feito no bloco transformed data.

### Blocos parameters & transformed parameters {.unnumbered}

O bloco `data` é onde são declaradas as variáveis que o usuário deve passar ao compilador, podendo ser interpretado como os argumentos de uma função. Já no bloco `transformed data`, é possível realizar operações sobre essas variáveis. Em resumo, o bloco `data` deve conter apenas declarações, não sendo permitido atribuir valores a variáveis dentro dele. Caso se queira atribuir ou modificar valores, isso deve ser feito no bloco `transformed data`.


### Bloco model {.unnumbered}

No bloco `model` são feitas todas as declarações probabilísticas, o que envolve definir uma distribuição para os dados condicionada aos parâmetros e uma distribuição para os próprios parâmetros. Essa especificação pode ser feita de duas formas: pela notação distribucional usual, em que se declara que uma variável segue determinada distribuição, ou por meio da palavra-chave `target`, que representa o logaritmo da densidade posterior não normalizada. O objetivo do algoritmo de amostragem será maximizar esse `target`.


### Bloco functions {.unnumbered}

O bloco `functions` serve para declarar funções que serão utilizadas ao longo do código Stan. As funções nessa sintaxe seguem a mesma lógica das funções escritas em C++, o que inclui a tipagem forte e a sintaxe de escopo.

## Argumentos importantes

O help pode ser acessado via `?rstan::sampling` ou `?rstan::stan`.

* `chains`: o número de cadeias que se deseja rodar
* `init`: aqui ficam armazenados os valores do chute inicial das cadeias. Esse argumento deve ser obrigatoriamente uma lista de listas em que, no primeiro nível, fica a cadeia e, no segundo nível, uma lista nomeada com os parâmetros especificados no `.stan` e cujos valores são o chute inicial da cadeia.
Note que deve sempre valer `length(init) == chains`.
No exemplo abaixo, o modelo tem dois parâmetros ($\alpha$ e $\beta$) e na primeira cadeia o chute inicial é $\alpha_0 = 2, \beta_0=3$; na segunda cadeia é  $\alpha_0 = -1, \beta_0$ é escolhido pelo STAN; na terceira cadeia $\beta_0=100$ e $\alpha$ é escolhido pelo STAN, pois não foi especificado.

```{r}
init =
  list(
    list(alpha = 2, beta = 3),
    list(alpha = -1, beta = "random"),
    list(beta = 100)
  )
```

<!--
::: {.callout-tip collapse="true"}

#### Sobre chutes iniciais 

Caso o usuário não especifique um chute incial, o algoritmo do STAN tenta escolher valores segundo a seguinte regra

Caso a regra resulte num valor impossível a priori, teremos a mensagem . Isso, em geral está associado a um modelo mal especifico ou a erros na escrita o script `.stan`.
:::
-->

* `warmup`: o número de iterações que serão excluídas, por default o STAN escolhe o warmup como sendo igual a metade das iterações.

<!--
::: {.callout-caution collapse="true"}
### Porque não é uma boa ideia diminuir o warmup?

É comum que

Essa filosofia é tão forte no pacote que não é possível alterar o valor do warmup uma vez que a amostragem foi feita. Assim, a função `rstan::extract` não aceita um argumento de warmup e nem é possível alterar esse atributo num objeto da classe `stanfit`, via `@`
:::
-->

* `iter`: o número total de iterações que desejamos rodar para cada uma das cadeias, em geral o STAN reclama caso sejam colocadas poucas iterações (adiante explicaremos o porque).

::: {.callout-note collapse="true"}
#### Conversando na torre de Babel

Em alguns softwares de estimação de distribuições (inclusive o CMDSTAN), `warmup` e `iter` podem ter significados diferentes dos do rstan. É possível que `iter` signifique o número de amostras que o programa vai tomar após o `warmup`, então o total de iterações é dado por `warmup` + `iter`. No caso do rstan o total de iterações é `iter` - e, nesse caso, o tamanho da amostra da posteriori é `iter` - `warmup`.
:::

* `cores`: especifica quantos núcleos do processador serão utilizados no processo de estimação. Como os algoritmos MCMC são sequenciais por natureza, a forma mais direta de ganhar eficiência é dedicar um núcleo a cada cadeia, rodando-as em paralelo.
* `data`: devem ser passados (por meio de uma lista) todos os objetos declarados no bloco `data` do arquivo `.stan`. É, essencialmente, a ponte entre o ambiente do R e o modelo especificado no Stan.
* `pars`: permite especificar quais parâmetros o algoritmo de estimação deve retornar. Caso não seja especificado, o Stan retorna todos os parâmetros declarados no bloco `parameters` por padrão.
* `seed`: define a semente utilizada para a geração dos valores iniciais e dos sorteios ao longo do algoritmo. É importante destacar que o Stan é um programa independente e utiliza seu próprio gerador de números aleatórios, separado do R. Por isso, definir uma semente na sessão do R com `set.seed()` não garante reprodutibilidade dos resultados do Stan — a semente deve ser definida diretamente no argumento `seed` da função de amostragem.
