---
title: "Introdução"
---

```{r}
#| include: false

library(tidyverse)
library(rstan)
library(coda)
library(deldir)
library(posterior)
library(shinystan)
```

::: {style="text-align: right"}
"Nunca ouviste passar o vento.<br>
O vento só fala do vento.<br>
O que lhe ouviste foi mentira,<br>
E a mentira está em ti."<br>
Pessoa
:::

## Sobre {.unnumbered}

Este é o [material auxiliar](https://github.com/carlosdemoura/2026_aula_stan_dani) da apresentação sobre STAN para a turma de Inferência Bayesiana (DCC/DEST-UFMG, 2026/1). Orgulhosamente feito em [Quarto](https://quarto.org/) e R!

## Setup do ambiente {.unnumbered}


```{r}
#| eval: false
pacotes_instalados = installed.packages()[,"Package"]
if (!"pak" %in% pacotes_instalados) install.packages("pak")

pacotes_necessarios = c("tidyverse", "rstan", "coda", "posterior", "shinystan", "survival", "broom", "rsample")

pacotes_necessarios |>
  setdiff(pacotes_instalados) |>
  {\(.) if (length(.)) pak::pak(.)}()

for (pak in pacotes_necessarios) {require(pak, character.only = T)}
```

# Referências {.unnumbered}

::: {#refs}
:::